#index:
#    path: /
#    controller: App\Controller\DefaultController::index

convert_to_pdf:
    path: /convert-to-pdf
    controller: App\Controller\ReponseReclamationController::convertToPdf
    methods: ['POST']

