#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
# config/routes.yaml
generate_qr_code:
    path: '/generate-qr-code/{id}'
    controller: 'App\Controller\YourController::generateQRCode'
