#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_voiture_delete:
    path: /voiture/{idv}
    controller: App\Controller\VoitureController::delete
    methods: DELETE
generate_pdf:
    path: /generate-pdf
    methods: [POST]
app_reponse_add:
    path: '/reponse/add/{commentaireId}'
    controller: App\Controller\HomeController::add
app_stats:
    path: /admin/stats
    controller: App\Controller\StatsController::index
