#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_reponse_add:
    path: '/reponse/add/{commentaireId}'
    controller: App\Controller\HomeController::add
app_stats:
    path: /admin/stats
    controller: App\Controller\StatsController::index
